# Generated by Django 2.2.6 on 2019-11-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mercury", "0004_auto_20191112_1256"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accelerationsensor",
            old_name="created_at",
            new_name="created_at_accel",
        ),
    ]
