# Generated by Django 2.2.6 on 2019-11-13 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercury', '0006_auto_20191113_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuellevelsensor',
            old_name='created_at',
            new_name='created_at_fl',
        ),
        migrations.RenameField(
            model_name='suspensionsensor',
            old_name='created_at',
            new_name='created_at_ss',
        ),
    ]
